### ISSUE TITLE
Get Alarm working

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#21]
.. Absolute and Relative time

So choose a move and set it to go at 4pm, or +3 hours

**Comment by MasterTailer** [comment]
That looks good to me!

⁣The Master Tailer​

**Comment by leinir** [comment]
Much good thinking there, that sounds about right for the logic of it all, yes :) A couple of details that might make life easier:

- Right now, BaseMovesPage just sends the commands directly, but to make life easier for you, so you can reuse that for picking a command there, i would suggest refactoring the sendCommand logic out, so that becomes a signal on BaseMovesPage, which TailMoves and TailLights both use (which will cause code duplication there), but which then means you can use BaseMovesPage to pick the alarm command as well, and show all four categories on the same page as well.
- i'd probably want to add the persisted stuff to the AppSettings entry, and then have the alarm functionality itself in a class similar to the IdleMode class which listens to those properties (it's perhaps a little overly indirect, but means we don't pollute our persistence layer with either presentation or logic).
- You can stick a FilterModel into the Alarm page to show the specific alarm by filtering on the Command role, which i also suggest is used for which particular command to set the alarm on, rather than e.g. name or model index. (can't remember what value the Command role is off the top of my head, but you can count your way to it the way it's done in BaseMovesPage for the Category role, or you can export the enum if you feel like it).

Hope that's helpful :)

**Comment by gilmanov-ildar** [comment]
@MasterTailer or @leinir, could you please record a video how it works with a real device. For example, we open `Tail Moves` view, click to `Slow Wag 1` and what is happen after? The video will help me a lot :)

**Comment by leinir** [comment]
Just pushed a change so BaseMovesPage only blocks input when the tail is moving when it is told to do so (and have told it to do so only on the TailMoves page). This will make it easier for you to do that picking thing i mentioned in my first point above :)

i don't have a real tail right now, but i am unsure how a video of that would really help you do this... though i can totally see why having a video of the thing in action would be cool anyway ;)

**Comment by gilmanov-ildar** [comment]
I offer to reuse `MoveLists` component for alarms. In this case we just need to add time settings to move lists and save them at persistent storage. And it is much better then do only one action on time.

@leinir, @MasterTailer, What do you think about that?

**Comment by gilmanov-ildar** [comment]
Hmm, but it seems we use `Move Lists` only as a library for complex actions, so it would be not nice to add a concrete time to that complex action. But later we can add that actions as sources to the Alarms.

**Comment by gilmanov-ildar** [comment]
Done:

1. Extracted `NamePicker` component from `MoveList`
2. Figured out how alarms views should look
3. Created stubs for `AlarmList.qml`
4. Created stubs for `Alarm` and `AlarmList` C++ classes

At the next week:

1. Link QML view with model classes to showing, editing and adding alarms
2. Load and store alarms to and from settings

**Comment by leinir** [comment]
> Hmm, but it seems we use `Move Lists` only as a library for complex actions, so it would be not nice to add a concrete time to that complex action. But later we can add that actions as sources to the Alarms.

Indeed, it would not make a lot of sense to add specific times into Move Lists, however it certainly would be nice for the alarm function to be able to also accept a move list as well as a single command for the alarm action :)

**Comment by gilmanov-ildar** [comment]
![image](https://user-images.githubusercontent.com/15459404/53112898-e7063b80-3572-11e9-80cd-53e17541b8b8.png)

![image](https://user-images.githubusercontent.com/15459404/53112972-11f08f80-3573-11e9-88a8-d00b5ba39db9.png)

![image](https://user-images.githubusercontent.com/15459404/53112920-f4232a80-3572-11e9-9a6b-19a8138524cd.png)

![image](https://user-images.githubusercontent.com/15459404/53112937-fdac9280-3572-11e9-9921-067fe0cc8232.png)

![image](https://user-images.githubusercontent.com/15459404/53113006-216fd880-3573-11e9-9ad1-17369081d25d.png)

1. Extracted shared components from `MoveLists.qml` and `MoveListEditor.qml`
2. Added `MessageBox.qml` component. Now we can easily show message boxes with the one command: `showMessageBox(qsTr(""))`
3. Added `DatePicker.qml` and `TimePicker.qml`
4. Load and store alarm list model
3.

**Comment by gilmanov-ildar** [comment]
https://github.com/MasterTailer/DIGITAiL/pull/40

**Comment by gilmanov-ildar** [comment]
Now user can only setup absolute date and time for alarm, but I think you want to add periodic tasks (each day, for example). And now we do not send the commands from app to devices.

**Comment by MasterTailer** [comment]
We dont need periodic ones, nice idea though.
