### ISSUE TITLE
Quick splash screen

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#4]
On app start

**Comment by MasterTailer** [comment]
![newlogo](https://user-images.githubusercontent.com/44520040/52225057-6b816a80-28a1-11e9-98c9-4b237367c719.JPG)

Add "DIGITAiL" underneath it.

Splash to hold for 5 seconds

**Comment by gilmanov-ildar** [comment]
As I got now it is no any splash screen, am I right?

**Comment by gilmanov-ildar** [comment]
And I suppose you need it only for Android version. Now I am building the app only for desktop.

**Comment by gilmanov-ildar** [comment]
@MasterTailer, @leinir, done. But now the icons are too small. But it depends on your taste and view. To have a good view and big enough images I should have a source image, and it would be nice if it would be a SVG file. (I am not sure that the attached to this card image is an original image because it has rough edges).

But anyway you could setup the new images at the `DIGITAiL/data/res/drawable-*` directories.

In one of my previous projects I have images with the following sizes:

* drawable-hdpi 482x482
* drawable-ldpi 242x242
* drawable-mdpi 322x322
* drawable-xhdpi 642x642
* drawable-xxhdpi 962x962

**Comment by gilmanov-ildar** [comment]
https://github.com/MasterTailer/DIGITAiL/pull/46

**Comment by MasterTailer** [comment]
Run movie first time the app is run, on the splash screen

**Comment by MasterTailer** [comment]
You could add an option in settings to make the movie run again after the first run.. But it defaults to run once.

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/86

Added new activity `SplashActivity` and run it by default with a video. User can tap to the video to skip it. And at the moment we show it at each startup of the application.

**Comment by MasterTailer** [comment]
..and you will allow it to be run only once..

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/89
